version: 0.1.0

id: "prebundle-aws-fsbp-iam"
name: "Prebundle: Review AWS IAM posture (FSBP)"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: policy-service-limitation
    name: Review policy service limitation
    decide:
      rego: !include policy-service-limitation/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include policy-service-limitation/decide.graphql
