version: 0.1.0

id: "prebundle-aws-fsbp-efs"
name: "Prebundle: Review AWS EFS posture (FSBP)"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: access-point-user-identity
    name: Review access point user identity
    decide:
      rego: !include access-point-user-identity/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include access-point-user-identity/decide.graphql
  - id: access-point-root-directory
    name: Review access point root directory
    decide:
      rego: !include access-point-root-directory/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include access-point-root-directory/decide.graphql
  - id: volume-backup-plan
    name: Review volume backup plan
    decide:
      rego: !include volume-backup-plan/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include volume-backup-plan/decide.graphql
