version: 0.1.0

id: "prebundle-aws-fsbp-dax"
name: "Prebundle: Review AWS DAX posture (FSBP)"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: cluster-encryption
    name: Review cluster encryption
    decide:
      rego: !include cluster-encryption/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include cluster-encryption/decide.graphql
