version: 0.1.0

id: "prebundle-googlecloud-dataproc"
name: "Prebundle: Review Google Cloud Dataproc posture"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: encryption-key
    name: Review that the Dataproc cluster is encrypted using customer-managed encryption key
    decide:
      rego: !include encryption-key/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
      input:
        schema: !include encryption-key/decide.graphql
