version: 0.1.0

id: "prebundle-googlecloud-credential"
name: "Prebundle: Review Google Cloud Credential posture"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: api-keys-usage
    name: Review API keys do not exist in Google Cloud projects
    decide:
      rego: !include api-keys-usage/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
      input:
        schema: !include api-keys-usage/decide.graphql
  - id: api-keys-scope
    name: Review scopes for Google Cloud API keys are limited
    decide:
      rego: !include api-keys-scope/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
      input:
        schema: !include api-keys-scope/decide.graphql
  - id: api-keys-restriction
    name: Review API Keys are restricted to usage by only specified hosts and apps
    decide:
      rego: !include api-keys-restriction/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
      input:
        schema: !include api-keys-restriction/decide.graphql
  - id: api-keys-rotation
    name: Review API keys are rotated within reasonable days
    decide:
      rego: !include api-keys-rotation/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
      input:
        schema: !include api-keys-rotation/decide.graphql
