version: 0.1.0

id: "prebundle-aws-fsbp-ecr"
name: "Prebundle: Review AWS ECR posture (FSBP)"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: repository-lifecycle-policy-config
    name: Review repository lifecycle policy config
    decide:
      rego: !include repository-lifecycle-policy-config/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include repository-lifecycle-policy-config/decide.graphql
  - id: repository-image-scan-config
    name: Review repository image scan config
    decide:
      rego: !include repository-image-scan-config/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include repository-image-scan-config/decide.graphql
  - id: repository-tag-immutability
    name: Review repository tag immutability
    decide:
      rego: !include repository-tag-immutability/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include repository-tag-immutability/decide.graphql
