version: 0.1.0

id: "prebundle-aws-config"
name: "Prebundle: Review AWS Config posture"

triggers:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  - id: recorder-status
    name: Review AWS Config is enabled in all regions
    decide:
      rego: !include recorder-status/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include recorder-status/decide.graphql
