version: 0.1.0

id: "prebundle-aws-cis-ec2"
name: "Prebundle: Review AWS EC2 posture (FSBP)"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: instance-imdsv2
    name: Review instance imdsv2
    decide:
      rego: !include instance-imdsv2/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include instance-imdsv2/decide.graphql
