version: 0.1.0

id: "prebundle-aws-s3"
name: "Prebundle: Review AWS S3 posture"

triggers:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  - id: bucket-access-logging
    name: Review the configuration of the bucket's access logging
    decide:
      rego: !include bucket-access-logging/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include bucket-access-logging/decide.graphql
  - id: bucket-encryption
    name: Review the encryption of buckets
    decide:
      rego: !include bucket-encryption/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include bucket-encryption/decide.graphql
  - id: bucket-mfa-delete
    name: Review the status of MFA delete
    decide:
      rego: !include bucket-mfa-delete/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include bucket-mfa-delete/decide.graphql
  - id: bucket-public-access
    name: Review the public accessibility of buckets
    decide:
      rego: !include bucket-public-access/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include bucket-public-access/decide.graphql
  - id: bucket-transport
    name: Review the bucket's transport
    decide:
      rego: !include bucket-transport/decide.rego
      with:
        resource_exceptions:
          type: resource_exception
          multiple: true
          description: A special list of resource exceptions
          values: []
        tag_exceptions:
          type: string
          multiple: true
          description: A list of AWS tags with which resources can have any settings automatically. For instance, if you include `Environment=production` for this value, all resources with `Environment=production` will be allowed automatically.
          values: []
      input:
        schema: !include bucket-transport/decide.graphql
