name: "Test Rego Policies"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: v0.70.0
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Run OPA tests
        run: |
          opa test -v --timeout 30s .
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: v0.70.0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Rego codes
        run: |
          opa fmt . --fail
